# Linux
linux:
	$(MAKE) -C helloworld linux && $(MAKE) -C drawx linux && $(MAKE) -C simplerain linux


# Windows (FIXME)
win32:
	$(MAKE) -C helloworld win32 && $(MAKE) -C drawx win32 && $(MAKE) -C simplerain win32


# Mac OS (TODO)


# All targets
all: linux

clean:
	$(MAKE) -C helloworld clean && $(MAKE) -C drawx clean && $(MAKE) -C simplerain clean
